version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: billmate-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - billmate-network

  auth-service:
    build: ../auth-service
    container_name: auth-service
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/auth_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - billmate-network

  billing-service:
    build: ../billing-service
    container_name: billing-service
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/billing_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - billmate-network

  api-gateway:
    build: ../api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - billing-service
    networks:
      - billmate-network

networks:
  billmate-network:
    driver: bridge

volumes:
  postgres-data:

